# High-volume Java example for exercising the scheduler with many cases.
entry = "Main"
lang = "Java"
args = []
target = "examples/java/massive/submissions"
timeout = 1500
threads = 12
checker = "Static"
format = "{name}_{id}_{filename}.{extension}"
orderby = "Id"

input = [
  "0\n", "1\n", "2\n", "3\n", "4\n", "5\n", "6\n", "7\n", "8\n", "9\n",
  "10\n", "11\n", "12\n", "13\n", "14\n", "15\n", "16\n", "17\n", "18\n", "19\n",
  "20\n", "21\n", "22\n", "23\n"
]

output = [
  "0\n", "1\n", "4\n", "9\n", "16\n", "25\n", "36\n", "49\n", "64\n", "81\n",
  "100\n", "121\n", "144\n", "169\n", "196\n", "225\n", "256\n", "289\n", "324\n", "361\n",
  "400\n", "441\n", "484\n", "529\n"
]

points = [
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1
]
